// locale
export const FETCH_LOCALE = 'FETCH_LOCALE';
export const FETCH_LOCALE_SUCCESS = 'FETCH_LOCALE_SUCCESS';
export const FETCH_LOCALE_FAILURE = 'FETCH_LOCALE_FAILURE';

// articles
export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAILURE = 'FETCH_ARTICLES_FAILURE';

// classify
export const FETCH_CLASSIFIES = 'FETCH_CLASSIFIES';
export const FETCH_CLASSIFIES_SUCCESS = 'FETCH_CLASSIFIES_SUCCESS';
export const FETCH_CLASSIFIES_FAILURE = 'FETCH_CLASSIFIES_FAILURE';

// links
export const FETCH_LINKS = 'FETCH_LINKS';
export const FETCH_LINKS_SUCCESS = 'FETCH_LINKS_SUCCESS';
export const FETCH_LINKS_FAILURE = 'FETCH_LINKS_FAILURE';
